Repository MobilityData/gtfs-validator, pull requests merged in 2020-04, with the labels that each got.

#57 Routes entities -- internal representation
  adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsDataRepository.java
  adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsDataRepositoryTest.java
  adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsSpecRepositoryTest.java
  domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/routes/Route.java
  domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/routes/RouteType.java
  domain/src/test/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/RouteTest.java
  domain/src/test/java/org/mobilitydata/gtfsvalidator/domain/entity/gtfs/RouteTypeTest.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ProcessParsedRoute.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/GtfsDataRepository.java
  usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ProcessParsedRouteTest.java
Labels: gtfs internal representation

#113 chore: Improve CLI Main.main() error messages
  application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/Main.java
Labels: enhancement

#110 Implement #95 - Implement ExecutionParameterRepository
  .gitignore
  README.md
  RELEASE.md
  adapter/parser/build.gradle
  adapter/parser/src/main/java/org/mobilitydata/gtfsvalidator/parser/ApacheExecParamParser.java
  adapter/parser/src/main/java/org/mobilitydata/gtfsvalidator/parser/JsonExecParamParser.java
  adapter/parser/src/test/java/org/mobilitydata/gtfsvalidator/parser/ApacheExecParamParserTest.java
  adapter/parser/src/test/java/org/mobilitydata/gtfsvalidator/parser/JsonExecParamParserTest.java
  adapter/repository/in-memory-simple/build.gradle
  adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryExecParamRepository.java
  adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryGtfsSpecRepository.java
  adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryValidationResultRepository.java
  adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/InMemoryExecParamRepositoryTest.java
  adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/NoticeMemoryConsumptionTest.java
  adapter/repository/in-memory-simple/src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
  application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/Main.java
  config/build.gradle
  config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java
  config/src/main/resources/default-execution-parameters.json
  domain/build.gradle
  domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/ExecParam.java
  domain/src/test/java/org/mobilitydata/gtfsvalidator/domain/entity/ExecParamTest.java
  usecase/build.gradle
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/CleanOrCreatePath.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/DownloadArchiveFromNetwork.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ExportResultAsFile.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/LogExecutionInfo.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ParseAllExecParam.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/PrintHelp.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/UnzipInputArchive.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/ExecParamRepository.java
  usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ExportResultAsFileTest.java
  usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ParseAllExecParamTest.java
Labels: enhancement

#118 Fix #117 - Change content of constant ZIP_KEY
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/ExecParamRepository.java
Labels: bug

#115 fix: Create output directory even when results file lock is held
  adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporter.java
  adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporter.java
  adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporterTest.java
  adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporterTest.java
  config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/CleanOrCreatePath.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/notice/base/ErrorNotice.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/notice/error/CouldNotCleanOrCreatePathNotice.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/ValidationResultRepository.java
Labels: enhancement
