Repository MobilityData/gtfs-validator, pull requests merged in 2020-11, with the labels that each got.

#462 URL from OpenMobilityData BART GTFS --> empty zip
  .github/workflows/end_to_end.yml
  config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java
  usecase/build.gradle
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/UnzipInputArchive.java
  usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/UnzipInputArchiveTest.java
  usecase/src/test/resources/nested_folders_sample.zip
  usecase/src/test/resources/valid_zip_sample.zip
  usecase/src/test/resources/zip_with_invalid_content_sample.zip
Labels: GitHub Action

#478 Improve end to end workflow clarity
  .github/workflows/end_to_end.yml
Labels: enhancement

#479 Rework report name to include both feed_publisher_name and agency_name when available
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/ExportResultAsFile.java
  usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/ExportResultAsFileTest.java
Labels: enhancement

#481 Always generate validation report
  .github/workflows/end_to_end.yml
  README.md
  RULES.md
  adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporter.java
  adapter/exporter/src/main/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporter.java
  adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/JsonNoticeExporterTest.java
  adapter/exporter/src/test/java/org/mobilitydata/gtfsvalidator/exporter/ProtobufNoticeExporterTest.java
  adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryExecParamRepository.java
  adapter/repository/in-memory-simple/src/main/java/org/mobilitydata/gtfsvalidator/db/InMemoryValidationResultRepository.java
  adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/InMemoryExecParamRepositoryTest.java
  adapter/repository/in-memory-simple/src/test/java/org/mobilitydata/gtfsvalidator/db/InMemoryValidationResultRepositoryTest.java
  adapter/utils/src/main/java/org/mobilitydata/gtfsvalidator/fileutils/CustomFileUtilsImpl.java
  adapter/utils/src/test/java/org/mobilitydata/gtfsvalidator/fileutils/CustomFileUtilsImplTest.java
  application/cli-app/src/main/java/org/mobilitydata/gtfsvalidator/cli/Main.java
  config/src/main/java/org/mobilitydata/gtfsvalidator/config/DefaultConfig.java
  domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/NoticeExporter.java
  domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/ErrorNotice.java
  domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/base/Notice.java
  domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/CannotDownloadArchiveFromNetworkNotice.java
  domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/FatalInternalErrorNotice.java
  domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/GtfsDatasetTooBigNotice.java
  domain/src/main/java/org/mobilitydata/gtfsvalidator/domain/entity/notice/error/OutOfMemoryNotice.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/DownloadArchiveFromNetwork.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/GenerateInfoNotice.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/HandleOutOfMemoryError.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/HandleUnsupportedException.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/RawFileRepository.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/port/ValidationResultRepository.java
  usecase/src/main/java/org/mobilitydata/gtfsvalidator/usecase/utils/CustomFileUtils.java
  usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/DownloadArchiveFromNetworkTest.java
  usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/HandleOutOfMemoryErrorTest.java
  usecase/src/test/java/org/mobilitydata/gtfsvalidator/usecase/HandleUnsupportedExceptionTest.java
Labels: enhancement

#490 update release documentation
  RELEASE.md
Labels: documentation
